In [ ]:
import random
import math

K = 3
# Define the input data
A = [[random.uniform(-1, 1) for _ in range(K)] for _ in range(K)]
B = [[random.uniform(-1, 1) for _ in range(K)] for _ in range(K)]
C = [[random.uniform(-1, 1) for _ in range(K)] for _ in range(K)]
# Input vector x
x = [random.uniform(-1, 1) for _ in range(K)]

In [136]:
# Define the sigmoid function
def sigmoid(value):
    return 1 / (1 + math.exp(-value))

def sigmoid_derivative(value):
    return sigmoid(value) * (1 - sigmoid(value))

def matrix_vector_multiplication(matrix, vector):
    if len(matrix) != len(matrix[0]) or len(matrix) != len(vector):
        raise ValueError("Matrix and vector dimensions don't match for multiplication")

    result = [0] * len(vector)
    for i in range(len(matrix)):
        for j in range(len(vector)):
            result[i] += matrix[i][j] * vector[j]

    return result

# Manual Backpropagation
def manual_backpropagation(x, A, B, C):
    K = len(x)
    
    # Initialze all other vectors to zero, of length K
    y, u, v, w = [0] * K, [0] * K, [0] * K, [0] * K

    # Forward propagation
    y = matrix_vector_multiplication(A, x)
    for i in range(K):
        u[i] = sigmoid(y[i])
    v = matrix_vector_multiplication(B, x)
    z = [u + v for u, v in zip(u, v)]
    w = matrix_vector_multiplication(C, z)

    L = sum(val ** 2 for val in w)

    print(f"Loss Manual Good: {L}")

    #Backpropagation
    #Compute gradients ∂L/∂A, ∂L/∂B, ∂L/∂C
    dL_dw = [2 * val for val in w]
    dL_dz = [dL_dw[i] for i in range(K)]
    dL_dy = [dL_dz[i] for i in range(K)]
    dL_dv = [dL_dy[i] * sigmoid_derivative(y[i]) for i in range(K)]

    dL_dC = [[dL_dw[i] * z[j] for j in range(K)] for i in range(K)]
    dL_dB = [[dL_dv[i] * x[j] for j in range(K)] for i in range(K)]
    dL_dA = [[dL_dy[i] * x[j] for j in range(K)] for i in range(K)]

    print("Gradient dL/dA:")
    for row in dL_dA:
        print(row)

    dL_dw = [2 * val for val in w]
    dL_dC = [[dL_dw[i] * z[j] for j in range(K)] for i in range(K)]

    dL_dz = [0] * K
    for i in range(K):
        dL_dz[i] = sum(dL_dw[j] * C[i][j] for j in range(K))

    dL_dv = [0] * K
    for i in range(K):
        dL_dv[i] = dL_dz[i]

    dL_dB = [[dL_dv[i] * x[j] for j in range(K)] for i in range(K)]

    dL_dy = [0] * K
    for i in range(K):
        dL_dy[i] = sum(dL_dz[j] * B[i][j] for j in range(K))
        dL_dy[i] *= y[i] * (1 - y[i])

    dL_dA = [[dL_dy[i] * x[j] for j in range(K)] for i in range(K)]
    print("Gradient dL/dA:")
    for row in dL_dA:
        print(row)


    return dL_dA, dL_dB, dL_dC

def manual_backpropagation_rounded(x, A, B, C):
    K = len(x)
    
    # Forward propagation
    y = [0] * K
    for i in range(K):
        y[i] = sum(A[i][j] * x[j] for j in range(K))
        y[i] = sigmoid(y[i])

    v = [0] * K
    for i in range(K):
        v[i] = sum(B[i][j] * x[j] for j in range(K))

    z = [u + v for u, v in zip(y, v)]

    w = [0] * K
    for i in range(K):
        w[i] = sum(C[i][j] * z[j] for j in range(K))

    for val in w:
        L = sum(val ** 2 for val in w)

    print(f"Loss Manual2: {L}")
    
    # Backpropagation ---- !!! Something wrong with this back propogation algorithm !!!
    # Compute gradients ∂L/∂A, ∂L/∂B, ∂L/∂C
    dL_dw = [round(2 * val, 4) for val in w]
    dL_dC = [[round(dL_dw[i] * z[j], 4) for j in range(K)] for i in range(K)]

    dL_dz = [0] * K
    for i in range(K):
        dL_dz[i] = sum(round(dL_dw[j] * C[i][j], 4) for j in range(K))

    dL_dv = [0] * K
    for i in range(K):
        dL_dv[i] = dL_dz[i]

    dL_dB = [[round(dL_dv[i] * x[j], 4) for j in range(K)] for i in range(K)]

    dL_dy = [0] * K
    for i in range(K):
        dL_dy[i] = sum(round(dL_dz[j] * B[i][j], 4) for j in range(K))
        dL_dy[i] *= round(y[i] * (1 - y[i]), 4)

    dL_dA = [[round(dL_dy[i] * x[j], 4) for j in range(K)] for i in range(K)]
    return dL_dA, dL_dB, dL_dC


def backwardpropagation(x, A, B, C):
    K = len(x)
    
    # Initialize gradients
    dA, dB, dC = [[0] * K for _ in range(K)], [[0] * K for _ in range(K)], [[0] * K for _ in range(K)]

    # Forward propagation
    y = matrix_vector_multiplication(A, x)
    u = [sigmoid(val) for val in y]
    v = matrix_vector_multiplication(B, x)
    z = [u_i + v_i for u_i, v_i in zip(u, v)]
    w = matrix_vector_multiplication(C, z)

    # Compute the loss L
    L = sum(val ** 2 for val in w)

    # Backpropagation
    # Gradients of L w.r.t. w
    dL_dw = [2 * val for val in w]

    # Gradients of L w.r.t. C
    for i in range(K):
        for j in range(K):
            dC[i][j] = dL_dw[i] * z[j]

    # Gradients of L w.r.t. z
    dL_dz = sum(dL_dw[i] * z[i] for i in range(K))

    # Gradients of L w.r.t. u and v
    dL_du = [dL_dz * sigmoid(y_i) * (1 - sigmoid(y_i)) for y_i in y]
    dL_dv = [dL_dz] * K  # Same gradient for all elements of v

    # Gradients of L w.r.t. A
    for i in range(K):
        for j in range(K):
            dA[i][j] = dL_du[i] * x[j]

    # Gradients of L w.r.t. B
    for i in range(K):
        for j in range(K):
            dB[i][j] = dL_dv[i] * x[j]

    return dA, dB, dC, L


# Manual Backpropagation
dL_dA_manual, dL_dB_manual, dL_dC_manual = manual_backpropagation(x, A, B, C)

dL_dA_manual_round, dL_dB_manual_round, dL_dC_manual_round = manual_backpropagation_rounded(x, A, B, C)

dL_dA_final, dL_dB_final, dL_dC_final, L = backwardpropagation(x, A, B, C)

#Print the gradients
print("--- Manual Backpropagation Gradient ∂L/∂A: ----")
for row in dL_dA_manual:
    print(row)

print("--- Manual Backpropagation Gradient Rounded ∂L/∂A: --- ")
for row in dL_dA_manual_round:
    print(row)

print("--- Automatic Differentiation with PyTorch Gradient ∂L/∂A: ---")
print(dL_dA_final)

# print("Manual Backpropagation Gradient ∂L/∂B:")
# for row in dL_dB_manual:
#     print(row)

# print("Automatic Differentiation with PyTorch Gradient ∂L/∂B:")
# print(dL_dB_torch)

# print("Manual Backpropagation Gradient ∂L/∂C:")
# for row in dL_dC_manual:
#     print(row)

# print("Automatic Differentiation with PyTorch Gradient ∂L/∂C:")
# print(dL_dC_torch)

Loss Manual Good: 0.6441052860636061
Gradient dL/dA:
[-0.9634435530157177, 0.3338766098092709, -0.49543344505552134]
[0.5473762111111067, -0.18969052528709854, 0.2814783296471856]
[-0.882387547274748, 0.30578705093810965, -0.4537518581675414]
Gradient dL/dA:
[0.004567639815161595, -0.001582893041883398, 0.002348826272504369]
[-0.08610838055021142, 0.029840434433632178, -0.04427967937572271]
[-1.8231132345920278, 0.6317908964761841, -0.9375030511263464]
Loss Manual2: 0.6441052860636061
Loss Automatic: 0.6441052556037903
--- Manual Backpropagation Gradient ∂L/∂A: ----
[0.004567639815161595, -0.001582893041883398, 0.002348826272504369]
[-0.08610838055021142, 0.029840434433632178, -0.04427967937572271]
[-1.8231132345920278, 0.6317908964761841, -0.9375030511263464]
--- Automatic Differentiation with PyTorch Gradient ∂L/∂A: ---
tensor([[-0.3001,  0.1040, -0.1543],
        [ 0.0129, -0.0045,  0.0066],
        [-0.0737,  0.0255, -0.0379]])
--- Automatic Differentiation with PyTorch Gradient ∂L

# Verify the gradients using libraries - Torch, mxnet

In [137]:
import torch

A_torch = torch.tensor(A, requires_grad=True, dtype=torch.float32)
B_torch = torch.tensor(B, requires_grad=True, dtype=torch.float32)
C_torch = torch.tensor(C, requires_grad=True, dtype=torch.float32)
x_torch = torch.tensor(x, dtype=torch.float32)

# Define the sigmoid function
def sigmoid(value):
    return 1 / (1 + torch.exp(-value))

def forwardpropagation_torch(x, A, B, C):
    y = torch.matmul(A, x.unsqueeze(1)).squeeze()
    u = sigmoid(y)
    v = torch.matmul(B, x.unsqueeze(1)).squeeze()
    z = u + v
    w = torch.matmul(C, z.unsqueeze(1)).squeeze()
    L = torch.norm(w, p=2)**2
    return L

def backwardpropagation_torch(L_torch):
    L_torch.backward()
    dA = A_torch.grad
    dB = B_torch.grad
    dC = C_torch.grad
    return dA, dB, dC

L_torch = forwardpropagation_torch(x_torch, A_torch, B_torch, C_torch)
dA_torch, dB_torch, dC_torch = backwardpropagation_torch(L_torch)


print(f"Gradients (torch) dL/dA:\n{dA_torch}")
print(f"Gradients (torch) dL/dB:\n{dB_torch}")
print(f"Gradients (torch) dL/dC:\n{dC_torch}")

Gradients (torch) dL/dA:
tensor([[-0.3001,  0.1040, -0.1543],
        [ 0.0129, -0.0045,  0.0066],
        [-0.0737,  0.0255, -0.0379]])
Gradients (torch) dL/dB:
tensor([[-1.2072,  0.4183, -0.6208],
        [ 0.0588, -0.0204,  0.0302],
        [-0.4221,  0.1463, -0.2171]])
Gradients (torch) dL/dC:
tensor([[ 0.9729,  0.5914,  0.2404],
        [-0.5527, -0.3360, -0.1366],
        [ 0.8910,  0.5417,  0.2201]])


In [138]:
import mxnet as mx
from mxnet import autograd

x_mx = mx.nd.array(x_torch.detach().numpy())
A_mx = mx.nd.array(A_torch.detach().numpy())
B_mx = mx.nd.array(B_torch.detach().numpy())
C_mx = mx.nd.array(C_torch.detach().numpy())

def sigmoid(value):
    return 1 / (1 + mx.nd.exp(-value))

def forwardpropagation_mx(x, A, B, C):
    y = mx.nd.dot(A, x)
    u = sigmoid(y)
    v = mx.nd.dot(B, x)
    z = u + v
    w = mx.nd.dot(C, z)
    L = mx.nd.norm(w) ** 2
    return L

def backwardpropagation_mx(L_mx):
    L_mx.backward()
    dA = A_mx.grad
    dB = B_mx.grad
    dC = C_mx.grad
    return dA, dB, dC

A_mx.attach_grad()
B_mx.attach_grad()
C_mx.attach_grad()

with autograd.record():
    L_mx = forwardpropagation_mx(x_mx, A_mx, B_mx, C_mx)

dA_mx, dB_mx, dC_mx = backwardpropagation_mx(L_mx)

print(f"Gradients (mx) dL/dA:\n{dA_mx}")
print(f"Gradients (mx) dL/dB:\n{dB_mx}")
print(f"Gradients (mx) dL/dC:\n{dC_mx}")


Gradients (mx) dL/dA:

[[-0.3000914   0.10399519 -0.15431656]
 [ 0.01288185 -0.00446414  0.00662426]
 [-0.07367561  0.02553192 -0.03788635]]
<NDArray 3x3 @cpu(0)>
Gradients (mx) dL/dB:

[[-1.2071898   0.4183457  -0.6207756 ]
 [ 0.05879717 -0.02037587  0.03023538]
 [-0.42214587  0.14629258 -0.21708089]]
<NDArray 3x3 @cpu(0)>
Gradients (mx) dL/dC:

[[ 0.97286165  0.5914468   0.24035469]
 [-0.55272716 -0.33602798 -0.13655648]
 [ 0.8910135   0.5416876   0.22013332]]
<NDArray 3x3 @cpu(0)>
